### ISSUE TITLE
AttributeError: 'Struct' object has no attribute '_Struct__keys'

### ISSUE THREAD

**Issue by lucionardelli** [mettienne/pysimplesoap#178]
Hi,

I'm writing because I've found a problem when trying to parse the definition of a WSDL.

When doing:

```
>>> from pysimplesoap.client import SoapClient
>>> SoapClient(wsdl="https://fwshomo.afip.gov.ar/wslsp/LspService?wsdl", trace=True)
```
I get a the following error:

`AttributeError: 'Struct' object has no attribute '_Struct__keys'`

When searching, I've found a similar issue: [https://github.com/mettienne/pysimplesoap/issues/158](https://github.com/mettienne/pysimplesoap/issues/158).

By following the proposed workaround:

```    
def __setitem__(self, key, value):
+        if not hasattr(self, '__keys'):
+            self.__keys = []
        if key not in self.__keys:
            self.__keys.append(key)
        dict.__setitem__(self, key, value)
```

I was able to parse the WSDL correctly, but i't seemed odd to me  that the old issue was solved on April 2015 but the problem came back!

The complete traceback of my code:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysimplesoap/client.py", line 169, in __init__
    self.services = wsdl and self.wsdl_parse(wsdl, cache=cache)
  File "pysimplesoap/client.py", line 868, in wsdl_parse
    services = self._xml_tree_to_services(wsdl, cache, force_download)
  File "pysimplesoap/client.py", line 811, in _xml_tree_to_services
    binding = ports[port['name']] = copy.deepcopy(bindings[binding_name])
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.6/copy.py", line 189, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.6/copy.py", line 334, in _reconstruct
    value = deepcopy(value, memo)
  File "/usr/lib/python2.6/copy.py", line 189, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.6/copy.py", line 335, in _reconstruct
    y[key] = value
  File "pysimplesoap/helpers.py", line 617, in __setitem__
    if key not in self.__keys:
AttributeError: 'Struct' object has no attribute '_Struct__keys'
```

**Comment by lucionardelli** [comment]
Further information:

I realized that the code was being tested in an old system, running Python 2.6.
I moved it to a different server and the everithing worked as expected. Something seems to have changed in `copy.py`

No support for v2.6 I guess, won't fix, right?

Thanks!
